server:
  port: 8888
#  tomcat:
#    uri-encoding: UTF-8

iocoder:
  # 名称
  name: iocoder
  # 版本
  version: 1.0-SNAPSHOT
  # 版权年份
  copyrightYear: 2022
  # 文件上传路径
  profile: C:\home\iocoder-pro\upload
  # 日志输出路径
  logfile: C:\home\logs
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

  captcha:
    timeout: 5m
    width: 160
    height: 60


spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  # 解决 springboot 2.6.x 整合 knife4j 3.0.x 依赖冲突 (启动报错：Failed to start bean 'documentationPluginsBootstrapper')
  # 整合 activiti 后 需要在 Knife4jConfig.class 中添加 webEndpointServletHandlerMapping 方法
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 允许循环依赖
  main:
    # 设置运行循环依赖
    allow-circular-references: true
    # 设置是否允许具有相同名称的Bean来覆盖之前的Bean
    allow-bean-definition-overriding: true

  application:
    name: iocoder

  # 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

# 文件服务
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: test

  # thymeleaf 模板配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增"
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    cache-enabled: false
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: com.iocoder.yudao.module.commons.core.mybatis.MyBaitsLogConfig

# 配置加密密钥
jasypt:
  encryptor:
    password: WkZuiShuai  #将秘钥作为启动时的命令行变量带入 java -jar iocoder-server.jar --jasypt.encryptor.password=WkZuiShuai
#    password 将秘钥作为启动时的应用环境变量带入  java -Djasypt.encryptor.password=WkZuiShuai -jar iocoder-server.jar
#    password: ${JASYPT_ENCRYPTOR_PASSWORD:}  #将加密秘钥设置为系统环境变量带入
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

# 系统默认配置
default:
  # 新增用户时的初始密码
  password: 666666


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyzxcvhnhcjmkchtctfdtxjyyvbiuzzjgxhusjdbjabjdhqbuysnjcbkayqbsubqisbianzjbxha
  # 令牌有效期（默认30分钟）
  expireTime: 30



