spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iocoder-pro?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: JASYPT_WK(xtW9Y1ih+n3oywwoWStlVze6vXJQMaCP1hvoLDH3QTBO/VgkUgxwrZGeHkL0xCl1)
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

iocoder:
  # 图片验证码
  captcha:
    enable: true



